Add vector search on overview page
milvus-io/milvus-insight pull request #175
Opened 2021-07-27 10:15 UTC by Tumao727

fix #170 
<img width="578" alt="search" src="https://user-images.githubusercontent.com/20420181/127137446-3731d00f-4c0c-4bb0-b1f0-18a1e0982b8b.png">

2021-07-27 10:16 UTC, shanghaikid requested changes

2021-07-27 10:16 UTC, shanghaikid commented on client/src/i18n/cn/button.ts
> +  vectorSearch: 'vector search',
'vector search' => 'Vector search'

2021-07-27 10:25 UTC, shanghaikid approved these changes

2021-07-27 11:01 UTC, nameczz commented on client/src/components/menu/NavMenu.tsx
> +  }, [defaultActive]);
why we need set it here?

2021-07-28 02:44 UTC, nameczz approved these changes

2021-07-28 02:46 UTC, merged