Create index add size info
milvus-io/milvus-insight pull request #266
Opened 2021-12-01 10:10 UTC by Tumao727

Signed-off-by: tumao <yan.wang@zilliz.com>

<img width="487" alt="sizing" src="https://user-images.githubusercontent.com/20420181/144214790-7c54a8f8-606d-48f4-b9e2-3fc8aa1d612d.png">

<img width="641" alt="tooltip" src="https://user-images.githubusercontent.com/20420181/144215023-c7f90cab-4aa7-42cc-8baa-0e902237cb35.png">

2021-12-01 10:11 UTC, shanghaikid commented
Please update insight docs as well.

2021-12-01 10:32 UTC, nameczz requested changes

2021-12-01 10:32 UTC, nameczz commented on client/src/pages/schema/SizingInfo.tsx
> +    '& .value': {},
what's this for?

2021-12-01 10:32 UTC, nameczz commented on client/src/pages/schema/Types.ts
> +  type: string;
type: float | bytes is better ?
Where did you use it ? I can't find it in this pr.

2021-12-02 01:43 UTC, nameczz approved these changes

2021-12-02 01:48 UTC, merged