add delete index
milvus-io/milvus-insight pull request #42
Opened 2021-06-23 06:34 UTC by Tumao727

fix #5

2021-06-23 06:35 UTC, shanghaikid requested changes

2021-06-23 06:35 UTC, shanghaikid commented on client/src/i18n/cn/index.ts
> +    'You are trying to delete a index. This action cannot be undone.',
delete an index

2021-06-23 06:35 UTC, shanghaikid commented on client/src/i18n/en/index.ts
> +    'You are trying to delete a index. This action cannot be undone.',
delete an index

2021-06-23 06:51 UTC, nameczz approved these changes

2021-06-23 07:01 UTC, Tumao727 commented
<img width="633" alt="delete" src="https://user-images.githubusercontent.com/20420181/123051023-e5dfc480-d433-11eb-98ea-829c041307b5.png">

2021-06-23 07:32 UTC, merged

2021-06-24 03:14 UTC, shanghaikid commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/milvus-io/milvus-insight/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: